---
title: "Language in Grampian"

output:
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: scroll
---

```{r setup, include=FALSE}
library(here)
library(tidyverse)
library(janitor)
library(sf)
library(flexdashboard)
library(mapview)
library(gt)
library(cowplot)
library(plotly)

theme_set(theme_cowplot())
```


```{r}
#load data and shapefiles 

simd_zones <- read_csv(here("data", "SIMD+2020v2+-+datazone+lookup.csv"))

simd_indicators <- read_csv(here("data", "SIMD2020v2_indicators.csv"))

datazone_sf <- st_read(here("data", "sc_dz_11.shp"), quiet = T)

ethnicity <- read_csv(here("data", "SNS Data Zone 2011 blk", "KS201SC.csv")) %>%
  clean_names()

english_skills <- read_csv(here("data", "SNS Data Zone 2011 blk", "QS213SC.csv")) %>%
  clean_names()

```

```{r}
#calculate percentages for english skills
#join SIMD files
#remove "%" and "*" and make numeric

english_skills <-
english_skills %>%
  mutate(
    across(
      understands_but_does_not_speak_read_or_write_english:no_skills_in_english,
      ~ .x/all_people_aged_3_and_over *100, 
      .names = "perc_{col}"),
    perc_cant_speak = perc_understands_but_does_not_speak_read_or_write_english + perc_reads_but_does_not_speak_or_write_english + perc_no_skills_in_english,
    perc_cant_read = perc_speaks_but_does_not_read_or_write_english + perc_understands_but_does_not_speak_read_or_write_english + perc_no_skills_in_english)

ethnicity <-
  ethnicity %>%
  mutate(
    across(
      white:other_ethnic_groups_other_ethnic_group,
      ~ .x/all_people *100, 
      .names = "perc_{col}"))

simd <- 
  left_join(simd_indicators, simd_zones, by = c("Data_Zone" = "DZ")) %>%
  left_join(., english_skills, by = c("Data_Zone" = "x1")) %>%
  left_join(., ethnicity, by = c("Data_Zone" = "x1"))

simd <- 
simd %>%
  mutate(across(everything(), ~ str_remove_all(., "%")),
         across(everything(), ~ str_remove_all(., "\\*")),
         across(all_people_aged_3_and_over:perc_other_ethnic_groups_other_ethnic_group, ~ as.numeric(.)))
```


```{r}
#select Aberdeen City, Aberdeenshire and Moray's data 
#join to make separate shapefiles

aberdeen <-
  simd %>%
  filter(Council_area == "Aberdeen City")

aberdeen_data_zones <- pull(aberdeen, Data_Zone)

aberdeen_sf <- filter(datazone_sf, DataZone %in% aberdeen_data_zones)

aberdeen_sf <-
  left_join(aberdeen_sf, aberdeen, by = c("DataZone" = "Data_Zone"))


aberdeenshire <-
  simd %>%
  filter(Council_area == "Aberdeenshire")

aberdeenshire_data_zones <- pull(aberdeenshire, Data_Zone)

aberdeenshire_sf <- filter(datazone_sf, DataZone %in% aberdeenshire_data_zones)

aberdeenshire_sf <-
  left_join(aberdeenshire_sf, aberdeenshire, by = c("DataZone" = "Data_Zone"))


moray <-
  simd %>%
  filter(Council_area == "Moray")

moray_data_zones <- pull(moray, Data_Zone)

moray_sf <- filter(datazone_sf, DataZone %in% moray_data_zones)

moray_sf <-
  left_join(moray_sf, moray, by = c("DataZone" = "Data_Zone"))

```




English skills in Aberdeen
=====================================

Row
-------------------------------------

###

```{r}
aberdeen_sf %>%
  select(DataZone, Name, Total_population, SIMD2020v2_Decile, perc_cant_speak) %>%
  mapview(
    map.types = "OpenStreetMap",
    zcol = "perc_cant_speak", 
    label = aberdeen_sf$Name,
    layer.name = "can't speak English (%)",
    alpha.regions = 0.8
    )
```


###

```{r}
#

aberdeen %>%
  select(Data_Zone, DZname, Total_population, perc_cant_speak, perc_white_polish, perc_asian_asian_scottish_or_asian_british, perc_african) %>%
   filter(perc_cant_speak >= 5) %>%
   arrange(desc(DZname)) %>%
  gt() %>%
  fmt_number(columns = vars(
    perc_cant_speak, perc_white_polish, perc_asian_asian_scottish_or_asian_british, perc_african), decimals = 0) %>%
  tab_header(
    title = "Aberdeen areas with most people who can't speak English", 
    subtitle = "Data zones with at least 5% of population who can't speak English") %>%
  cols_label(
    Data_Zone = "Data Zone",
    DZname = "Area", 
    Total_population = "Population", 
    perc_cant_speak = "Can't speak English (%)",
    perc_white_polish = "ethnically Polish (%)",
    perc_asian_asian_scottish_or_asian_british = "ethnically Asian (%)",
    perc_african = "ethnically African (%)")  %>%
  tab_options(container.height = 400)
```


English skills in Aberdeenshire
=====================================

Row
-------------------------------------

###

```{r}
aberdeenshire_sf %>%
  select(DataZone, Name, Total_population, SIMD2020v2_Decile, perc_cant_speak) %>%
  mapview(
    map.types = "OpenStreetMap",
    zcol = "perc_cant_speak", 
    label = aberdeenshire_sf$Name,
    layer.name = "can't speak English (%)",
    alpha.regions = 0.8
    )
```


###

```{r}
#

aberdeenshire %>%
  select(Data_Zone, DZname, Total_population, perc_cant_speak, perc_white_polish, perc_asian_asian_scottish_or_asian_british, perc_african) %>%
   filter(perc_cant_speak >= 5) %>%
   arrange(DZname) %>%
  gt() %>%
  fmt_number(columns = vars(
    perc_cant_speak, perc_white_polish, perc_asian_asian_scottish_or_asian_british, perc_african), decimals = 0) %>%
  tab_header(
    title = "Aberdeenshire areas with most people who can't speak English", 
    subtitle = "Data zones with at least 5% of population who can't speak English") %>%
  cols_label(
    Data_Zone = "Data Zone",
    DZname = "Area", 
    Total_population = "Population", 
    perc_cant_speak = "Can't speak English (%)",
    perc_white_polish = "ethnically Polish (%)",
    perc_asian_asian_scottish_or_asian_british = "ethnically Asian (%)",
    perc_african = "ethnically African (%)")  %>%
  tab_options(container.height = 400)
```


English skills in Moray
=====================================

Row
-------------------------------------

###

```{r}
moray_sf %>%
  select(DataZone, Name, Total_population, SIMD2020v2_Decile, perc_cant_speak) %>%
  mapview(
    map.types = "OpenStreetMap",
    zcol = "perc_cant_speak", 
    label = moray_sf$Name,
    layer.name = "can't speak English (%)",
    alpha.regions = 0.8
    )
```


###

```{r}
#

moray %>%
  select(Data_Zone, DZname, Total_population, perc_cant_speak, perc_white_polish, perc_asian_asian_scottish_or_asian_british, perc_african) %>%
   filter(perc_cant_speak >= 4) %>%
   arrange(DZname) %>%
  gt() %>%
  fmt_number(columns = vars(
    perc_cant_speak, perc_white_polish, perc_asian_asian_scottish_or_asian_british, perc_african), decimals = 0) %>%
  tab_header(
    title = "Moray areas with most people who can't speak English", 
    subtitle = "Data zones with at least 5% of population who can't speak English") %>%
  cols_label(
    Data_Zone = "Data Zone",
    DZname = "Area", 
    Total_population = "Population", 
    perc_cant_speak = "Can't speak English (%)",
    perc_white_polish = "ethnically Polish (%)",
    perc_asian_asian_scottish_or_asian_british = "ethnically Asian (%)",
    perc_african = "ethnically African (%)")  %>%
  tab_options(container.height = 400)
```


Sources
=====================================

Row
-------------------------------------
###

English skills and ethnicity data from 2011 Scotland Census
https://www.scotlandscensus.gov.uk/ods-web/data-warehouse.html 

English skills from file QS213SC, Ethnicity from file KS201SC 

Map shapefiles from 
https://data.gov.uk/dataset/ab9f1f20-3b7f-4efa-9bd2-239acf63b540/data-zone-boundaries-2011

Code and data at https://github.com/JessButler/language


